name: Multi-Stage GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build stage
        run: |
          echo "Build stage running"
          ls -l

  test:
    runs-on: ubuntu-latest
    needs: build   # This makes test run AFTER build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test stage'
        run: |
          echo Test stage running
          echo "All tests passed"
